# Generated by Django 3.2.5 on 2021-07-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='hello', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopcategory',
            name='image',
            field=models.ImageField(default='hel', upload_to=''),
            preserve_default=False,
        ),
    ]
