# Generated by Django 3.2.5 on 2021-07-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_auto_20210727_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='shopcategory',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
