# Generated by Django 3.2.5 on 2021-07-27 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_auto_20210727_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
