# Generated by Django 3.2.5 on 2021-08-13 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_remove_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_category_shop', to='admin_app.shopcategory')),
            ],
        ),
    ]
