# Generated by Django 3.2.5 on 2021-07-23 13:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='name must be Alpha', regex='^[a-zA-Z ]*$')], verbose_name='Your name')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='Phone number')),
                ('admin', models.BooleanField(default=False)),
                ('seller', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='SellerRequest',
            fields=[
                ('seller_name', models.CharField(max_length=100, verbose_name='Seller name')),
                ('shop_name', models.CharField(max_length=100, verbose_name='Shop name')),
                ('contact_location', models.CharField(max_length=100, verbose_name='Contact location')),
                ('contact_number', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='Contact number')),
                ('shop_business_address', models.TextField(verbose_name='Shop business address')),
                ('accepted', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('accept_by', models.ForeignKey(blank=True, limit_choices_to={'admin': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.shopcategory')),
            ],
        ),
    ]
